export const REQUEST_HOME_POSTS = 'REQUEST_HOME_POSTS'
export const RECEIVE_HOME_POSTS = 'RECEIVE_HOME_POSTS'

export const REQUEST_USERS = 'REQUEST_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'

export const REQUEST_SEARCH_USERS = 'REQUEST_SEARCH_USERS'
export const RECEIVE_SEARCH_USERS = 'RECEIVE_SEARCH_USERS'
export const SEARCH_USERS_INPUT_CHANGE = 'SEARCH_USERS_INPUT_CHANGE'

export const REQUEST_USER_POSTS = 'REQUEST_USER_POSTS'
export const RECEIVE_USER_POSTS = 'RECEIVE_USER_POSTS'

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const REQUEST_THREAD = 'REQUEST_THREAD'
export const RECEIVE_THREAD = 'RECEIVE_THREAD'

export const SEND_NEW_COMMENT = 'SEND_NEW_COMMENT'
export const RECEIVE_NEW_COMMENT = 'RECEIVE_NEW_COMMENT'
export const FAILED_NEW_COMMENT = 'FAILED_NEW_COMMENT'

export const SEND_NEW_POST = 'SEND_NEW_POST'
export const RECEIVE_NEW_POST = 'RECEIVE_NEW_POST'
export const FAILED_NEW_POST = 'FAILED_NEW_POST'

export const SWITCH_NEW_POST_MODE = 'SWITCH_NEW_POST_MODE'

export const SEND_NEW_THREAD = 'SEND_NEW_THREAD'
export const RECEIVE_NEW_THREAD = 'RECEIVE_NEW_THREAD'
export const FAILED_NEW_THREAD = 'FAILED_NEW_THREAD'

export const SWITCH_NEW_THREAD_MODE = 'SWITCH_NEW_THREAD_MODE'

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN'
export const RECEIVE_SIGN_IN = 'RECEIVE_SIGN_IN'
export const FAILED_SIGN_IN = 'FAILED_SIGN_IN'

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP'
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP'
export const FAILED_SIGN_UP = 'FAILED_SIGN_UP'

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT'
export const RECEIVE_SIGN_OUT = 'RECEIVE_SIGN_OUT'
export const FAILED_SIGN_OUT = 'FAILED_SIGN_OUT'

export const REQUEST_LOGGED_IN_USER = 'REQUEST_LOGGED_IN_USER'
export const RECEIVE_LOGGED_IN_USER = 'RECEIVE_LOGGED_IN_USER'

export const SWITCH_SIGNIN_MODE = 'SWITCH_SIGNIN_MODE'

export const NEW_POST_INPUT_CHANGE_FILE = 'NEW_POST_INPUT_CHANGE_FILE'
export const NEW_POST_INPUT_CHANGE_ANSWER = 'NEW_POST_INPUT_CHANGE_ANSWER'
export const NEW_POST_INPUT_CLEAR = 'NEW_POST_INPUT_CLEAR'
export const NEW_POST_CLOSE_DIALOG = 'NEW_POST_CLOSE_DIALOG'

export const NEW_THREAD_INPUT_CHANGE_FILE = 'NEW_THREAD_INPUT_CHANGE_FILE'
export const NEW_THREAD_INPUT_CHANGE_ANSWER = 'NEW_THREAD_INPUT_CHANGE_ANSWER'
export const NEW_THREAD_INPUT_CLEAR = 'NEW_THREAD_INPUT_CLEAR'
export const NEW_THREAD_CLOSE_DIALOG = 'NEW_THREAD_CLOSE_DIALOG'

export const NEW_COMMENT_INPUT_CHANGE_COMMENT = 'NEW_COMMENT_INPUT_CHANGE_COMMENT'
export const NEW_COMMENT_INPUT_CLEAR = 'NEW_COMMENT_INPUT_CLEAR'
export const NEW_COMMENT_CLOSE_DIALOG = 'NEW_COMMENT_CLOSE_DIALOG'

export const SETTINGS_INPUT_CHANGE_CURRENT_PASSWORD = 'SETTINGS_INPUT_CHANGE_CURRENT_PASSWORD'
export const SETTINGS_INPUT_CHANGE_NEW_PASSWORD = 'SETTINGS_INPUT_CHANGE_NEW_PASSWORD'
export const SETTINGS_INPUT_CHANGE_NEW_PASSWORD_CONFIRM = 'SETTINGS_INPUT_CHANGE_NEW_PASSWORD_CONFIRM'
export const SETTINGS_INPUT_CLEAR_PASSWORD = 'SETTINGS_INPUT_CLEAR_PASSWORD'
export const SETTINGS_CLOSE_DIALOG_PASSWORD = 'SETTINGS_CLOSE_DIALOG_PASSWORD'
export const SETTINGS_INPUT_CHANGE_FILE = 'SETTINGS_INPUT_CHANGE_FILE'
export const SETTINGS_INPUT_CLEAR_FILE = 'SETTINGS_INPUT_CLEAR_FILE'
export const SETTINGS_CLOSE_DIALOG_FILE = 'SETTINGS_CLOSE_DIALOG_FILE'

export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE'
export const LOGIN_INPUT_CLEAR = 'LOGIN_INPUT_CLEAR'

export const REQUEST_UPDATE_PASSWORD = 'REQUEST_UPDATE_PASSWORD'
export const RECEIVE_UPDATE_PASSWORD = 'RECEIVE_UPDATE_PASSWORD'
export const FAILED_UPDATE_PASSWORD = 'FAILED_UPDATE_PASSWORD'

export const REQUEST_UPDATE_AVATAR = 'REQUEST_UPDATE_AVATAR'
export const RECEIVE_UPDATE_AVATAR = 'RECEIVE_UPDATE_AVATAR'
export const FAILED_UPDATE_AVATAR = 'FAILED_UPDATE_AVATAR'
