export const REQUEST_HOME_POSTS = 'REQUEST_HOME_POSTS'
export const RECEIVE_HOME_POSTS = 'RECEIVE_HOME_POSTS'

export const REQUEST_THREAD = 'REQUEST_THREAD'
export const RECEIVE_THREAD = 'RECEIVE_THREAD'

export const SEND_NEW_COMMENT = 'SEND_NEW_COMMENT'
export const RECEIVE_NEW_COMMENT = 'RECEIVE_NEW_COMMENT'

export const SEND_NEW_POST = 'SEND_NEW_POST'
export const RECEIVE_NEW_POST = 'RECEIVE_NEW_POST'

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN'
export const RECEIVE_SIGN_IN = 'RECEIVE_SIGN_IN'
export const FAILED_SIGN_IN = 'FAILED_SIGN_IN'

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP'
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP'
export const FAILED_SIGN_UP = 'FAILED_SIGN_UP'

export const SWITCH_SIGNIN_MODE = 'SWITCH_SIGNIN_MODE'
